### ISSUE TITLE
Error: [404:invalid_request_error] The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by emilBeBri** [bakks/butterfish#14] opened 2023-07-11 15:22 UTC
Hi so as per this announcement:

https://openai.com/blog/gpt-4-api-general-availability

everyone including me finally have access to gtp 4. but when i try:

```
bfp -m 'gpt-4' 'which language model are you?'
```

I get this:

```
Error: [404:invalid_request_error] The model: `gpt-4` does not exist
```
works fine with:

```
bfp -m 'gpt-3.5-turbo' 'which language model are you?'

```

Best,
Emil

**Comment by bakks** [comment] 2023-07-11 21:51
Hey @emilBeBri - I'm not able to reproduce this problem, passing `gpt-4` in as the model is working for me. I would try the following:
1. [Create a new OpenAI API key](https://platform.openai.com/account/api-keys) and replace your current key in `~/.config/butterfish/butterfish.env`
2. Upgrade butterfish (most recent version is v0.1.1)

I bet that (1) will resolve the problem but let me know if it doesn't.

**Comment by emilBeBri** [comment] 2023-07-12 10:20
Hi! Ok so I made a new key and that didn't help - tried making two actually to be sure. I can see that both have been used when using 

```

butterfish prompt 'which language model are you?' -m 'gpt-3.5-turbo'

```

but 

```
butterfish prompt 'which language model are you?' -m 'gpt-4'

```
errors out  all the same. so a new key does not do anything it seems.
 

running the go install to update  gives me:

```

go install github.com/bakks/butterfish/cmd/butterfish@latest


>go: github.com/bakks/butterfish/cmd/butterfish@latest (in github.com/bakks/butterfish@v0.1.1):
>        The go.mod file for the module providing named packages contains one or
>        more replace directives. It must not contain directives that would cause
>        it to be interpreted differently than if it were the main module.

```

searching for this on google does not give any apparent solution, other than it seems to be related to the switch from `go get` to `go install`. (`go get` is deprecated, tried it too)

there is an issue about it here, but I'm not familiar with go so I can't really make anything out of it:

https://github.com/golang/go/issues/44840

**Comment by bakks** [comment] 2023-07-12 19:37
Ok I fixed the `go install`, I hadn't realized that was broken. That should now work, but I suspect probably won't fix the issue. Still investigating.

**Comment by bakks** [comment] 2023-07-12 20:11
@emilBeBri If that doesn't solve the GPT-4 issue for you can you paste a screenshot of what you see at https://platform.openai.com/account/rate-limits ?

**Comment by emilBeBri** [comment] 2023-07-13 10:07
Updated butterfish with Go just now and works great. 


Hmm that's interesting.  I don't see gtp-4 there. But didn't that announcement say that it was available for all paying API customers? Just read it again, and checked my settings doesn't seem like you're supposed to 'enable' the access in someway. Or maybe they're just rolling it out slow and it will be available during the coming weeks (but they didn't mention that in the announcement, either).



![scrot_2023-07-13_12-05-07](https://github.com/bakks/butterfish/assets/964816/8e3ae813-56ad-44d4-b9f3-e8ad2251612f)

**Comment by bakks** [comment] 2023-07-17 22:45
@emilBeBri I talked to someone at OpenAI, apparently they don't turn on GPT-4 until you successfully pay an invoice (this is a fraud prevention measure). So if you turned on billing this month, I bet it won't enable GPT-4 until early next month after the next billing cycle. Hope that helps.

**Comment by emilBeBri** [comment] 2023-07-18 05:36
Hi yes that's what I got out of it too. 

I couldn't understand it though because I've been using butterfish on a regular basis (since 3.5 is a little too simple for many purposes I find) . But for some reason they haven't billed me for it, like at all....! Must be a bug, or because my use has been so neglible,  because now that I've created a new api key and used it for whisper, I got a small bill yesterday. 

Mystery solved :)

**Closed** 2023-07-18 05:37 UTC
